
# Site Settings

title: Mike Meldgaard  # Your Title 
subtitle: Software Developer / Datamatiker Student
email: meldgaardmike@gmail.com  # Your Email
description: >-  
  Software Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://double-em.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: xplor4r
github_username:  Zxited

# Navigation 

urls:
    - text: About
      url: /
    - text: Portefølje
      url: /blog
    #- text: Shop
    #  url : /shop
    #- text: Sample Page
    #  url: /sample-page
    #- text: Contact Me
    #  url : /contact

# Author Details

author_logo: noimage.jpg
author: Mike Meldgaard
author_bio: Software Developer / Datamatiker 4. Sem. Student, Produktgruppe 15, Procesvejledning 8, ERFA Machine Learning 2, ERFA DevOps
author_email: "meldgaardmike@gmail.com"
author_location: Denmark
author_website_url: "https://double-em.github.io"

# social links
#twitter_username: xplor4r
github_username:  Zxited
#facebook_username: sujay.kundu2
#linkedin_username: sujaykundu
#behance_username: sujaykundu
#instagram_username: xplor4r
#medium_username: sujaykundu
#telegram_username: sujaykundu
#dribbble_username: sujaykundu777
#flickr_username: sujaykundu777

# Choose what to show ( true - display or false - don't display)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

author_work_experiences: 
            - company_name: Miralix
              company_logo: miralix.png
              company_url: https://miralix.dk
              designation: Customer Service Specialist
              description: Customer Support, Diagnosis and Error Correction, Software / Server Solutions Setups and Upgrades
              visibility: true
            - company_name: #Microsoft
              company_logo: noimage.jpg
              company_url: #https://microsoft.com
              designation: Electrician
              description: House and Powerplant Installations
              visibility: true

author_education_details:
              - college_logo: ucl.jpg
                college_name: UCL - Erhvervsakademi og Professionshøjskole
                college_url: https://ucl.dk
                college_degree: Erhvervsakademisk
                description: Datamatiker
                visibility: true
              - college_logo: sde.svg
                college_name: Syddansk Erhvervsskole
                college_url: https://sde.dk
                college_degree: Erhvervsuddannelse
                description: IT Supporter
                visibility: true

author_project_details:
              - project_thumbnail: mobileAppIcon.png
                project_title: Trendlog Production Administrator
                project_description: Mobile Application that let's a user see and get predictions on their production and future errors or maintenance.
                project_url: https://github.io
                visibility: true
              - project_thumbnail: programmingebooks.png
                project_title: Programming Ebooks
                project_description: A Platform to easily find and read programming books
                project_url: https://programmingebooks.com
                visibility: false
                
#for comments using disqus
disqus_shortname: 

# wakatime username
wakatime_username: 

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

kramdown:
  input: GFM

# pagination of posts
paginate: 500
per_page: 1
paginate_path: "/blog/page/:num/"

# Search ( add algolia credentials below )
algolia:
  application_id: D9WA1YKTRS # add your algolia app id
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: [] 
  nodes_to_index: 'article' 
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9b # add algolia search only api key 


# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Shop 

collections:
 - products

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build