
# Site Settings

title: Mike Meldgaard  # Your Title 
subtitle: Software Developer Student 
email: meldgaardmike@gmail.com  # Your Email
description: >-  
  Software Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zxited.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: xplor4r
github_username:  Zxited

# Navigation 

urls:
    - text: About
      url: /
    - text: Blog
      url: /blog
    #- text: Shop
    #  url : /shop
    - text: Sample Page
      url: /sample-page
    - text: Contact Me
      url : /contact

# Author Details

author_logo: #profile.jpg
author: Mike Meldgaard
author_bio: Hi, My Name is Sujay Kundu. I love to Code and Design. devlopr-jekyll is a theme built for developers.  
author_email: "meldgaardmike@gmail.com"
author_location: Denmark
author_website_url: "https://zxited.github.io"

# social links
#twitter_username: xplor4r
github_username:  Zxited
#facebook_username: sujay.kundu2
#linkedin_username: sujaykundu
#behance_username: sujaykundu
#instagram_username: xplor4r
#medium_username: sujaykundu
#telegram_username: sujaykundu
#dribbble_username: sujaykundu777
#flickr_username: sujaykundu777

# Choose what to show ( true - display or false - don't display)
show_author_work_experiences: false
show_author_education_details: false
show_author_project_details: true

author_work_experiences: 
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Trendlog Productoin Administrator
                project_description: Mobile Application that let's a user see and get predition on their production and future errors or maintenance.
                project_url: https://github.io
                visibility: true
              - project_thumbnail: programmingebooks.png
                project_title: Programming Ebooks
                project_description: A Platform to easily find and read programming books
                project_url: https://programmingebooks.com
                visibility: false
                
#for comments using disqus
disqus_shortname: sujay-kundu  

# wakatime username
wakatime_username: sujaykundu777

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# pagination of posts
paginate: 4
per_page: 5
paginate_path: "/blog/page/:num/"

# Search ( add algolia credentials below )
algolia:
  application_id: D9WA1YKTRS # add your algolia app id
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: [] 
  nodes_to_index: 'article' 
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9b # add algolia search only api key 


# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Shop 

collections:
 - products

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build